enum EnvironmentEnum {
    TWILIO_SID = 'TWILIO_SID',

    TWILIO_AUTH_TOKEN = 'TWILIO_AUTH_TOKEN',

    APP_NAME = 'APP_NAME',

    APP_DOMAIN = 'APP_DOMAIN',

    CONFERENCE_ROOM_NAME = 'CONFERENCE_ROOM_NAME',

    DIAL_SIP_INTERFACE = 'DIAL_SIP_INTERFACE',

    PORT = 'PORT',

}

export default EnvironmentEnum;
